# Copyright 2011 The vp8-go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=code.google.com/p/vp8-go/vp8
GOFILES=\
	decode.go\
	idct.go\
	partition.go\
	pred.go\
	predfunc.go\
	quant.go\
	reconstruct.go\
	token.go\

include $(GOROOT)/src/Make.pkg

